easy_admin:
#titre de l'application
    formats:
        date: 'd/m/Y'
        datetime: 'd/m/Y h:i'
    site_name: 'SEPJT'

    list:
        actions:
            - { name: 'new', icon: 'plus', label: 'Ajouter'}
            - { name: 'show', icon: 'search', label: 'Afficher'}
            - { name: 'edit', icon: 'pencil', label: 'Modifier' }
            - { name: 'delete', icon: 'trash', label: 'Supprimer'}

        batch_actions: ['delete']

    entities:
        Project:
            class: App\Entity\Project
            list:
                title : 'Liste des projets'
                fields:
                    - { property: 'name', label: 'Nom' }
                    - { property: 'startDate', label: 'Date de début' , type_options: { widget: 'single_text' }}
                    - { property: 'endDate', label: 'Date de fin' , type_options: { widget: 'single_text' }}


            show :
                title : 'Afficher projet'
                fields:
                    - { property: 'name', label: 'Nom' }
                    - { property: 'startDate', label: 'Date de début' , type_options: { widget: 'single_text' }}
                    - { property: 'endDate', label: 'Date de fin' , type_options: { widget: 'single_text' }}
                    - { property: 'Description', label: 'Description' }
                    - { property: 'location', label: 'Lieu' }
                    - { property: 'tasks', label: 'Tâches' }

            edit :
                title : 'Modifier projet'
                fields:
                    - { property: 'name', label: 'Nom' }
                    - { property: 'startDate', label: 'Date de début' , type_options: { widget: 'single_text' }}
                    - { property: 'endDate', label: 'Date de fin' , type_options: { widget: 'single_text' }}
                    - { property: 'Description', label: 'Description' }
                    - { property: 'location', label: 'Lieu' }
                item_permission: 'ROLE_ADMIN'
            new :
                title : 'Ajouter un nouveau projet'
                fields:
                    - { property: 'name', label: 'Nom' }
                    - { property: 'startDate', label: 'Date de début' , type_options: { widget: 'single_text' }}
                    - { property: 'endDate', label: 'Date de fin' , type_options: { widget: 'single_text' }}
                    - { property: 'Description', label: 'Description' }
                    - { property: 'location', label: 'Lieu' }
                item_permission: 'ROLE_ADMIN'
            delete:
                item_permission: 'ROLE_ADMIN'
        Task:
            class: App\Entity\Task
            list:
                title: 'Liste des tâches'
                fields:
                    - { property: 'name', label: 'Nom' }
                    - { property: 'startDate', label: 'Date de début' , type_options: { widget: 'single_text' }}
                    - { property: 'endDate', label: 'Date de fin' , type_options: { widget: 'single_text' }}
                    - { property: 'project', label: 'Projet' }


            show :
                title : 'Afficher tâche'
                fields:
                    - { property: 'name', label: 'Nom' }
                    - { property: 'startDate', label: 'Date de début' , type_options: { widget: 'single_text' }}
                    - { property: 'endDate', label: 'Date de fin' , type_options: { widget: 'single_text' }}
                    - { property: 'project', label: 'Projet' }
                    - { property: 'workers', label: 'Ouvriers' }
                    - { property: 'equipment', label: 'Matériels' }

            edit :
                title : 'Modifier tâche'
                fields:
                    - { property: 'name', label: 'Nom' }
                    - { property: 'startDate', label: 'Date de début' , type_options: { widget: 'single_text' }}
                    - { property: 'endDate', label: 'Date de fin' , type_options: { widget: 'single_text' }}
                    - { property: 'project', label: 'Projet' }
                item_permission: 'ROLE_ADMIN'
            new :
                title : 'Ajouter tâche'
                fields:
                    - { property: 'name', label: 'Nom' }
                    - { property: 'startDate', label: 'Date de début', type_options: { widget: 'single_text' }}
                    - { property: 'endDate', label: 'Date de fin' , type_options: { widget: 'single_text' }}
                    - { property: 'project', label: 'Projet' }
                item_permission: 'ROLE_ADMIN'
            delete:
                item_permission: 'ROLE_ADMIN'
        Worker:
            class: App\Entity\Worker
            list:
                title: 'Liste des ouvriers'
                fields:
                    - { property: 'fullName', label: 'Nom et Prénom' }
                    - { property: 'specialty', label: 'Spécialité' }
                    - { property: 'task', label: 'Tâche' }

            new :
                title : 'Ajouter un nouveau ouvrier'
                fields:
                    - { property: 'fullName', label: 'Nom et Prénom' }
                    - { property: 'specialty', label: 'Spécialité' }
                    - { property: 'task', label: 'Tâche' }
            edit :
                title : 'Modifier ouvrier'
                fields:
                    - { property: 'fullName', label: 'Nom et Prénom' }
                    - { property: 'specialty', label: 'Spécialité' }
                    - { property: 'task', label: 'Tâche' }
            show :
                title : 'Afficher ouvrier'
                fields:
                    - { property: 'fullName', label: 'Nom et Prénom' }
                    - { property: 'specialty', label: 'Spécialité' }
                    - { property: 'task', label: 'Tâche' }
        Equipment:
            class: App\Entity\Equipment
            list:
                title: 'Liste des matériels'
                fields:
                    - { property: 'name', label: 'Nom' }
                    - { property: 'quantity', label: 'Quantité' }
                    - { property: 'task', label: 'Tâche' }

            new :
                title : 'Ajouter un nouveau matériel'
                fields:
                    - { property: 'name', label: 'Nom' }
                    - { property: 'quantity', label: 'Quantité' }
                    - { property: 'task', label: 'Tâche' }
            edit :
                title : 'Modifier ouvrier'
                fields:
                    - { property: 'name', label: 'Nom' }
                    - { property: 'quantity', label: 'Quantité' }
                    - { property: 'task', label: 'Tâche' }
            show :
                title : 'Afficher ouvrier'
                fields:
                    - { property: 'name', label: 'Nom' }
                    - { property: 'quantity', label: 'Quantité' }
                    - { property: 'task', label: 'Tâche' }
        Contact:
            class: App\Entity\Contact
            list:
                title: 'Liste des message'
                fields:
                    - { property: 'name', label: 'Nom' }
                    - { property: 'email', label: 'Adresse de messagerie' }
                    - { property: 'object', label: 'Objet' }
            show :
                title : 'Afficher message'
                fields:
                    - { property: 'name', label: 'Nom' }
                    - { property: 'email', label: 'Adresse de messagerie' }
                    - { property: 'object', label: 'Objet' }
                    - { property: 'message', label: 'Message' }
            disabled_actions: ['new','delete','edit']
        User:
            class: App\Entity\User
            label: 'Utilisateur'
            list:
                title: 'Liste des utilisaterus'
                fields:
                    - { property: 'email', label: 'Adresse de messagerie' }
                    - { property: 'roles', label: 'Roles' }
            new :
                title : 'Ajouter un nouveau utilisateur'
                fields:
                    - { property: 'email', label: 'Adresse de messagerie' }
                    - { property: 'roles', label: 'Roles' }
                    - { property: 'password', label: 'Mot de passe' }
            edit :
                title : 'Modifier utilisateur'
                fields:
                    - { property: 'email', label: 'Adresse de messagerie' }
                    - { property: 'roles', label: 'Roles' }
                    - { property: 'password', label: 'Mot de passe' }
            show :
                title : 'Afficher utilisateur'
                fields:
                    - { property: 'email', label: 'Adresse de messagerie' }
                    - { property: 'roles', label: 'Roles' }
            form:
                fields:
                    - { property: 'email', type: 'email'}
                    - { property: 'password', type: 'password'}
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }
    design:
        # menu principale
        menu:
            - { label: 'Application'}
            - { entity: 'Project', label: 'Projet', icon: 'project-diagram'  }
            - { entity: 'Task', label: 'Tâche', icon: 'tasks' }
            - { entity: 'Worker', label: 'Ouvrier', icon: 'hard-hat' }
            - { entity: 'Equipment', label: 'Matériel', icon: 'hammer' }
            - { entity: 'Contact', label: 'Contact', icon: 'envelope' }
            - { label: 'Administration' , permission: 'ROLE_ADMIN'}
            - { entity: 'User', permission: 'ROLE_ADMIN', icon: 'user' }

